"Updated image tag to ${{ needs.image-tag.outputs.build_id }}"
airqo-platform/AirQo-api pull request #1773
Opened 2023-06-29 10:56 UTC by petermark23

**_WHAT DOES THIS PR DO?_**

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - []()
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

2023-07-10 07:53 UTC, 123MwanjeMike requested changes
Thanks @petermark23 
I left a few comments

2023-07-10 07:53 UTC, 123MwanjeMike commented on .github/workflows/deploy-apis-to-production.yml
> +            propertyPath: "image.new_property"
Hi @petermark23 
What is the `new_property` value?
Could you be meaning `tag`?

2023-07-10 07:53 UTC, 123MwanjeMike commented on k8s/predict/values-prod.yaml
> +        memory: 16000Mi
Could we also correct this indenting?

2023-07-10 07:53 UTC, 123MwanjeMike commented on .github/workflows/deploy-apis-to-production.yml
> +          context: src/predict/jobs/new_directory
what is the `new_directory`?
Could we specify the exact directory.

2023-07-10 07:53 UTC, 123MwanjeMike commented on .github/workflows/deploy-apis-to-production.yml
> +          tags: ${{ env.REGISTRY_URL }}/${{ env.PROJECT_ID }}/airqo-predict-places-air-quality:latest-update
Let's use `latest` tag and not `latest-update`

2023-07-11 17:59 UTC, Psalmz777 commented
@123MwanjeMike looks like Peter made changes ,I have made a few correction ,please review again

2023-07-12 02:52 UTC, 123MwanjeMike requested changes
Thanks @petermark23 and @Psalmz777 
I’ve left some more comments on where I we can improve.

2023-07-12 02:52 UTC, 123MwanjeMike commented on .github/workflows/deploy-apis-to-production.yml
> +<<<<<<< HEAD
Let’s have this line removed

2023-07-12 02:52 UTC, 123MwanjeMike commented on .github/workflows/deploy-apis-to-production.yml
> +          tags: ${{ env.REGISTRY_URL }}/${{ env.PROJECT_ID }}/airqo-predict-places-air-quality:${{ needs.image-tag.outputs.build_id }},${{ env.REGISTRY_URL }}/${{ env.PROJECT_ID }}/stage-airqo-predic
Why are we tagging this production image with the `stage` word in the tag name?

2023-07-12 02:52 UTC, 123MwanjeMike commented on .github/workflows/deploy-apis-to-production.yml
> +          tags: ${{ env.REGISTRY_URL }}/${{ env.PROJECT_ID }}/airqo-predict-places-air-quality:${{ needs.image-tag.outputs.build_id }},${{ env.REGISTRY_URL }}/${{ env.PROJECT_ID }}/stage-airqo-predic
Can we remove the `stage` word in this production image tag name?

2023-07-12 02:52 UTC, 123MwanjeMike commented on .github/workflows/deploy-apis-to-production.yml
> +            valueFile: "k8s/predict/new_directory/values-prod.yaml"
I still see an unexpected `new_directory` in the path. Could it still be an oversight?

2023-07-12 02:52 UTC, 123MwanjeMike commented on .github/workflows/deploy-apis-to-production.yml
> +=======
Can we remove these conflict resolution lines 1701 and 1702

2023-07-12 02:52 UTC, 123MwanjeMike commented on k8s/predict/values-prod.yaml
> +        memory: 16000Mi
Thanks

2023-07-12 02:52 UTC, 123MwanjeMike commented on .github/workflows/deploy-apis-to-production.yml
> +            valueFile: "k8s/predict/new_directory/values-prod.yaml"
Let’s remove `new_directory` from the path

2023-07-12 08:48 UTC, Psalmz777 approved these changes

2023-07-12 09:50 UTC, merged