Run-airflow read me for window
airqo-platform/AirQo-api pull request #2256
Opened 2023-10-10 15:31 UTC by wabinyai

**_WHAT DOES THIS PR DO?_**
Updating Read Me for WINDOW users

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - []()
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

2023-10-10 21:30 UTC, BenjaminSsempala approved these changes

2023-10-11 06:44 UTC, Mnoble-19 requested changes

2023-10-11 06:44 UTC, Mnoble-19 commented on src/airflow/run-airflow-only.sh
> +set DOCKER_BUILDKIT=1
Hi @wabinyai, thanks for this. 
One change though, this is just a bash script  & not the microservice's  README, so what you'll do is indicate all these lines  as  comments i.e . 
```
#For windows users
#steps to follow
```

2023-10-13 07:16 UTC, Mnoble-19 approved these changes

2023-10-13 13:08 UTC, merged