reporting API
airqo-platform/AirQo-api pull request #3036
Opened 2024-02-14 14:13 UTC by wabinyai

**_WHAT DOES THIS PR DO?_**
The API intend to easy reporting for each grid
Example how to run 
http://127.0.0.1:5000/airqoreports
{
    "grid_id": "64b7ba65d7249f0029fecdbd",
    "start_time": "2023-01-01T00:00",
    "end_time": "2023-12-30T00:00"
}
 
- [ ] Item 1
- [ ] Item 2

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - []
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

- [ ] Analytics: [Link to Analytics README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/analytics#readme)
- [ ] Auth Service: [Link to Auth Service README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/auth-service#readme)
- [ ] Calibrate: [Link to Calibrate README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/calibrate#readme)
- [ ] Data Proxy: [Link to Data Proxy README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/data-proxy#readme)
- [ ] Device Monitoring: [Link to Device Monitoring README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/device-monitoring#readme)
- [ ] Device Registry: [Link to Device Registry README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/device-registry#readme)
- [ ] Device Status: [Link to Device Status README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/device-status#readme)
- [ ] Device Uptime: [Link to Device Uptime README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/device-uptime#readme)
- [ ] Exceedances: [Link to Exceedances README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/exceedances#readme)
- [ ] Firebase: [Link to Firebase README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/firebase)
- [ ] GP Model: [Link to GP Model README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/gp-model#readme)
- [ ] Incentives: [Link to Incentives README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/incentives#readme)
- [ ] Kafka Connectors: [Link to Kafka Connectors](https://github.com/airqo-platform/AirQo-api/tree/staging/src/kafka-connectors)
- [ ] Locate: [Link to Locate README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/locate#readme)
- [ ] Metadata: [Link to Metadata README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/meta-data#readme)
- [ ] Predict: [Link to Predict README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/predict#readme)
- [ ] Spatial: [Link to Spatial](https://github.com/airqo-platform/AirQo-api/tree/staging/src/spatial)
- [ ] View: [Link to View README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/view#readme)
- [ ] Workflows: [Link to Workflows README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/workflows#readme)

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [ ] Endpoint 1
- [ ] Endpoint 2

**_ARE THERE ANY RELATED PRs?_**

- [ ] Related PR 1
- [ ] Related PR 2

2024-02-14 23:29 UTC, Baalmart reviewed
Hi @wabinyai , thanks for this.
Please note that this PR has some merge conflicts that need to be resolved.
Please resolve them accordingly.

2024-02-17 08:40 UTC, sserurich requested changes
- ensure the url on line 24 is read from the config file,
-update the naming for the routes as discussed

2024-02-17 15:08 UTC, wabinyai commented
> * ensure the url on line 24 is read from the config file,
>   -update the naming for the routes as discussed

This was resolved

2024-02-17 15:53 UTC, wabinyai commented
> While the time is local, the GMT should also reflect the local GMT. This is for Lagos and we are on GMT+1
> 
> ![image](https://private-user-images.githubusercontent.com/32173551/305632690-4a699a36-d2b1-40d4-b41d-4642181a23a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxODMwODcsIm5iZiI6MTcwODE4Mjc4NywicGF0aCI6Ii8zMjE3MzU1MS8zMDU2MzI2OTAtNGE2OTlhMzYtZDJiMS00MGQ0LWI0MWQtNDY0MjE4MWEyM2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE1MTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMTJmNzc5MDQ5MWVkYmMzZTU1M2Y1NDg0ZDk0NTAyN2Q4NDYwNWE2MmRkZTVkNTY1ZGVhMzUyMGI3N2NkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w9JentrGn5utvbWaaddKNFsI33GReUzyz9LgzoHiNnw)

The issue has been resolved instead of GMT it shows +01 for Nigeria +0300 for Uganda
![image](https://github.com/airqo-platform/AirQo-api/assets/6958665/e809d5e3-054b-46d0-a31f-aeb737caf156)
![image](https://github.com/airqo-platform/AirQo-api/assets/6958665/e128a59b-3e31-4848-8b33-1f6b6142ffeb)

2024-02-19 13:42 UTC, BenjaminSsempala approved these changes

2024-02-19 17:25 UTC, uman95 approved these changes
Works fine

2024-02-19 18:07 UTC, Baalmart approved these changes

2024-02-19 18:09 UTC, Baalmart requested changes
Hi @wabinyai , just have a small review comment....similar to what @sserurich already requested. Appears it is not yet resolved.

2024-02-19 18:09 UTC, Baalmart commented on src/analytics/config.py
> +    GRID_URL = "https://platform.airqo.net/api/v2/devices/measurements/grids/"
Hi @wabinyai , please have this URL read from a config file.

2024-02-19 18:13 UTC, Baalmart approved these changes

2024-02-19 18:15 UTC, merged