Getis-Ord Gi statistic
airqo-platform/AirQo-api pull request #3058
Opened 2024-02-24 23:17 UTC by wabinyai

**_WHAT DOES THIS PR DO?_**
The Getis-Ord Gi* statistic is a spatial autocorrelation statistic used to analyze the spatial distribution of a variable, such as PM2.5 pollution levels. It measures whether high or low values of the variable are clustered in space. Specifically, it compares the observed spatial clustering of high or low values to what would be expected under spatial randomness.

For PM2.5 pollution, the Gi* statistic can help identify areas where high levels of pollution are clustered, indicating potential hotspots of pollution concentration. This information is valuable for environmental research and policy-making, as it allows for targeted interventions to mitigate pollution in affected areas and protect public health.

- [ ] Item 1
- [ ] Item 2

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - []
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

- [ ] Analytics: [Link to Analytics README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/analytics#readme)
- [ ] Auth Service: [Link to Auth Service README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/auth-service#readme)
- [ ] Calibrate: [Link to Calibrate README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/calibrate#readme)
- [ ] Data Proxy: [Link to Data Proxy README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/data-proxy#readme)
- [ ] Device Monitoring: [Link to Device Monitoring README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/device-monitoring#readme)
- [ ] Device Registry: [Link to Device Registry README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/device-registry#readme)
- [ ] Device Status: [Link to Device Status README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/device-status#readme)
- [ ] Device Uptime: [Link to Device Uptime README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/device-uptime#readme)
- [ ] Exceedances: [Link to Exceedances README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/exceedances#readme)
- [ ] Firebase: [Link to Firebase README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/firebase)
- [ ] GP Model: [Link to GP Model README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/gp-model#readme)
- [ ] Incentives: [Link to Incentives README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/incentives#readme)
- [ ] Kafka Connectors: [Link to Kafka Connectors](https://github.com/airqo-platform/AirQo-api/tree/staging/src/kafka-connectors)
- [ ] Locate: [Link to Locate README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/locate#readme)
- [ ] Metadata: [Link to Metadata README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/meta-data#readme)
- [ ] Predict: [Link to Predict README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/predict#readme)
- [ ] Spatial: [Link to Spatial](https://github.com/airqo-platform/AirQo-api/tree/staging/src/spatial)
- [ ] View: [Link to View README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/view#readme)
- [ ] Workflows: [Link to Workflows README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/workflows#readme)

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [ ] Endpoint 1
- [ ] Endpoint 2

**_ARE THERE ANY RELATED PRs?_**

- [ ] Related PR 1
- [ ] Related PR 2

2024-02-24 23:26 UTC, wabinyai commented on src/spatial/job/getis_ord/services/getis_services.py
> +            return jsonify({'error': f'An error occurred: {str(e)}'}), 500  # Include specific error message
issue has been resolved

2024-02-28 07:50 UTC, BenjaminSsempala approved these changes

2024-02-28 08:06 UTC, katendejericho5 approved these changes
LGTM

2024-02-29 03:39 UTC, Baalmart requested changes
Hi @wabinyai , thanks for this. Just have a small comment --- attached as a screenshot. Also, please note that the staging for spatial micro has just been updated, you might want to get (pull) the latest staging changes you made and merge into your branch asap. Thanks!
<img width="613" alt="Screenshot 2024-02-29 at 06 35 14" src="https://github.com/airqo-platform/AirQo-api/assets/1590213/6fc224ec-dd8a-4755-80e0-0e005a2aa703">

2024-03-06 06:53 UTC, closed without merging