Predict unit tests
airqo-platform/AirQo-api pull request #316
Opened 2021-04-06 11:01 UTC by lilly-muyama

# Unit tests for the Predict Microservice

**_WHAT DOES THIS PR DO?_**
This PR creates unit tests for the predict microservice

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
https://airqoteam.atlassian.net/browse/PLAT-432

**_WHAT IS THE LINK TO THE PR BRANCH_**

**_HOW DO I TEST OUT THIS PR?_**
1. Git clone this repo
2. `cd src/predict` 
3.  `env\scripts\activate` for Windows and `source env/bin/activate` for Linux
4. `pip install -r requirements.txt`
5. `pytest`

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
N/A

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

2021-04-07 09:20 UTC, Baalmart reviewed
Thanks @lilly-muyama , looking good. :) 
A few thoughts/questions in addition to another specific review comment in the PR follow:

1. Could we have the test files alongside the files they are testing? WHY? For easy navigation during refactoring works in the near future.
2. Is there a possibility of categorising/grouping/tagging our tests so that a person can specify which ones to run?

2021-04-07 09:20 UTC, Baalmart commented on src/predict/tests/test_datamanagement.py
> +from models.datamanagement import calculate_hourly_averages, get_channel_id, get_all_coordinates
For unit tests, could we mock the data and not make a direct call to the actual database? More notes here:[ 1](https://stackoverflow.com/questions/51988331/using-a-fake-mongodb-for-pytest-testing) and [2](https://pypi.org/project/pytest-mongodb/)

2021-04-15 09:11 UTC, bobturneruk commented
Looks like there's a lot of excellent work here. I'm trying to run on my machine and hit this error on pip install:

```
ERROR: Cannot install -r requirements.txt (line 28), -r requirements.txt (line 31) and google-resumable-media==0.5.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested google-resumable-media==0.5.1
    google-cloud-bigquery 1.25.0 depends on google-resumable-media<0.6dev and >=0.5.0
    google-cloud-storage 1.30.0 depends on google-resumable-media<2.0dev and >=0.6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

I'm using `conda` for virtual environments, but I think this is likely to be a conflict that affects all virtual environments. Could the version requirements be relaxed @lilly-muyama?

2021-04-15 09:14 UTC, lilly-muyama commented
> 
> 
> Looks like there's a lot of excellent work here. I'm trying to run on my machine and hit this error on pip install:
> 
> ```
> ERROR: Cannot install -r requirements.txt (line 28), -r requirements.txt (line 31) and google-resumable-media==0.5.1 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested google-resumable-media==0.5.1
>     google-cloud-bigquery 1.25.0 depends on google-resumable-media<0.6dev and >=0.5.0
>     google-cloud-storage 1.30.0 depends on google-resumable-media<2.0dev and >=0.6.0
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
> ```
> 
> I'm using `conda` for virtual environments, but I think this is likely to be a conflict that affects all virtual environments. Could the version requirements be relaxed @lilly-muyama?

@bobturneruk I am currently making many updates to this PR and I will look into this too. Thanks.

2021-04-15 09:23 UTC, bobturneruk commented
Great. Thanks. I'm keen to help. Another suggestion is to implement some CI as you're going along (based on this https://github.com/airqo-platform/AirQo-modules/blob/staging/.github/workflows/python-app.yml but without `tox`). This will help ensure that the tests pass on a clean install without user intervention. See also https://github.com/pykale/pykale/blob/master/.github/workflows/test.yml

2021-04-21 09:28 UTC, ja-odur requested changes
The failing tests are mainly due to unhandled exceptions in the codebase, It will be better to actually test for these specific exceptions (ensuring the tests pass). In the future when these exceptions are handled, the tests will fail ( and then they can be fixed by the "implementer")

2021-04-21 10:35 UTC, sserurich commented
> The failing tests are mainly due to unhandled exceptions in the codebase, It will be better to actually test for these specific exceptions (ensuring the tests pass). In the future when these exceptions are handled, the tests will fail ( and then they can be fixed by the "implementer")

![image](https://user-images.githubusercontent.com/8258229/115539861-27be8400-a2a6-11eb-8c6f-68b7d2f04ee7.png)
This is comment applies to what I get.

2022-11-07 06:39 UTC, closed without merging