Implementaion  for stationary sources of pollution
airqo-platform/AirQo-api pull request #3945
Opened 2024-11-28 10:37 UTC by pronapro

## Description

[Implementation for API endpoints for stationary sources of pollution ]

## Changes Made

- [x] Made API endpoints for Data insertion and retrieval.
- [x] Data insertion endpoints take in the image, duration of interest and radius of area of interest and return the geometry, confidence score and location and environment profiles identified.
- [x] Retrieving endpoints return data saved in the database by parameters such as confidence score.

## Testing

- [x] Tested locally
- [ ] Tested against staging environment
- [ ] Relevant tests passed: [List test names]

## Affected Services

- [ ] Which services were modified:
  - [ ] Spatial microservice

2024-11-28 13:50 UTC, Baalmart requested changes
Thanks. @pronapro for this. The future is indeed bright.

- I can see that the deploy preview for the PR is failing. Please investigate this.
- Can you please reach out (individually) to @wabinyai and @Mnoble-19 to thoroughly review this PR?

Thanks again.

2025-04-14 13:15 UTC, wabinyai reviewed
Sort out these comments

2025-04-14 13:15 UTC, wabinyai commented on src/spatial/.dockerignore
> +#google_application_credentials.json
I do not think this needs to be removed.  We do not want to accidentally add these to the PR

2025-04-14 13:15 UTC, wabinyai commented on src/spatial/requirements.txt
> -python-dotenv~=1.0.1
**python-dotenv** Is used by  other models in this microservice keep it

2025-04-14 13:15 UTC, wabinyai commented on src/spatial/requirements.txt
> -earthengine-api~=1.1.1
**earthengine-api~=1.1.1** do not remove this. It is also being used in the microservice, especially to pull satellite data.

2025-04-14 13:15 UTC, wabinyai commented on src/spatial/.dockerignore
> +#.env
Do not comment out **.env** is being used, we do not need to accidentally display out secrets

2025-06-13 15:11 UTC, sserurich reviewed
some feedback from code scanning related to improving security (when printing exception messages) , can address them now or we can initiate other PRs to improve security of the codebase
![image](https://github.com/user-attachments/assets/88f65729-9aa8-4fd4-b8fc-b9003a83deac)

2025-06-13 15:15 UTC, sserurich approved these changes
The functionality works as expected. Tested locally, left a comment but doesn't stop approving.

2025-07-10 07:46 UTC, wabinyai approved these changes
Looks ok, the comments I left were addressed

2026-06-11 14:40 UTC, closed without merging