review validations for creating defaults and also fix saving periods
airqo-platform/AirQo-api pull request #713
Opened 2022-02-10 08:46 UTC by Baalmart

# review validations for creating defaults and also fix saving periods

**_WHAT DOES THIS PR DO?_**
review validations for creating defaults and also fix saving periods

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
[PLART-992]

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/hotfix-chart-defaults-PLAT-992

**_HOW DO I TEST OUT THIS PR?_**
README file

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [ ] [Create defaults](https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/auth-service/create-defaults#create-defaults)
- [ ] [Update defaults](https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/auth-service/create-defaults#update-default)

2022-02-10 09:42 UTC, Baalmart reviewed
just adding some guiding notes for your review exercise. @ja-odur

2022-02-10 09:42 UTC, Baalmart commented on src/auth-service/routes/api-v1.js
> +        .isIn(["daily", "hourly", "monthly, diurnal"])
the `diurnal `validation has been added from here.... @ja-odur

2022-02-10 09:42 UTC, Baalmart commented on src/auth-service/models/Defaults.js
> +  {
Schema has been update to reflect the sub-fields for the period field. @ja-odur

2022-02-10 09:42 UTC, Baalmart commented on src/auth-service/routes/api-v1.js
> +        .notEmpty()
For the update of defaults endpoint (PUT), this particular validation for the` period `field is misbehaving. But shall continue investigating it tomorrow. @ja-odur

2022-02-15 13:13 UTC, Baalmart commented on src/auth-service/routes/api-v1.js
> +        .isIn(["daily", "hourly", "monthly, diurnal"])
Resolved

2022-02-15 13:13 UTC, Baalmart commented on src/auth-service/routes/api-v1.js
> +        .notEmpty()
this was also resolved

2022-03-07 13:57 UTC, 123MwanjeMike reviewed
Great stuff. Just a minor concern tho

2022-03-08 06:17 UTC, Baalmart commented on src/auth-service/routes/api-v1.js
> +        .withMessage("period.value is is missing in your request"),
Yeah, this is a typo. Let me fix it. Thanks!

2022-03-08 06:26 UTC, Baalmart commented on src/auth-service/routes/api-v1.js
> +        .withMessage("period.value is is missing in your request"),
This has been addressed in my most recent commit. Thanks again!

2022-03-08 06:53 UTC, 123MwanjeMike approved these changes
LGTM

2022-03-09 06:38 UTC, ja-odur requested changes
@Baalmart The update endpoint is not recognising `diurnal` as a valid frequency
![image](https://user-images.githubusercontent.com/39955305/157386194-422a0a46-3648-43f6-ad4c-0f2ae0047069.png)

2022-03-09 06:47 UTC, Baalmart commented
> @Baalmart The update endpoint is not recognising `diurnal` as a valid frequency ![image](https://user-images.githubusercontent.com/39955305/157386194-422a0a46-3648-43f6-ad4c-0f2ae0047069.png)

This has been addressed, please PULL and proceed. @ja-odur

2022-03-09 06:54 UTC, ja-odur approved these changes
LGTM

2022-03-09 06:56 UTC, merged